[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pylint.'MESSAGES CONTROL']
disable = "missing-module-docstring"

[tool.pylint.BASIC]
good-names = "db,df"
